---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-stores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/viktorwa3/terraform-k8s.git
    targetRevision: master
    path: gitops/manifests/secret-stores
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # the CRD only exists once external-secrets is synced
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
